# Generated by Django 4.1.6 on 2023-03-31 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_pet_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.PositiveIntegerField(blank=True, help_text='em anos', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='raca',
            field=models.CharField(blank=True, help_text='use SRD caso não saiba ou não exista uma raça definida', max_length=60, null=True, verbose_name='Raça'),
        ),
    ]
