# Generated by Django 4.1.6 on 2023-05-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_pet_data_cadastro_alter_pet_idade_alter_pet_raca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro'),
        ),
    ]
