# Generated by Django 4.1.6 on 2023-05-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_data_cadastro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('-data_cadastro',)},
        ),
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
