# Generated by Django 4.1.6 on 2023-05-27 00:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=60, verbose_name='título')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('conteudo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='conteúdo')),
                ('imagem', models.ImageField(upload_to='noticias')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['data_cadastro'],
            },
        ),
    ]
