# Generated by Django 4.1.6 on 2023-05-11 00:17

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', sorl.thumbnail.fields.ImageField(upload_to='banners', verbose_name='imagem')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('mobile', models.BooleanField(default=False)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='banner.banner', verbose_name='banner')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
            },
        ),
    ]
